### ISSUE TITLE
Coffee lake mod its worked?

### ISSUE THREAD

**Issue by yehbr** [BrushXue/Z170i-Pro-Gaming-OpenCore#1]
Hey! I have z170i-Pro-Gaming motherboard and i want use cpu i5 9400f (I know about firmware bios and using pinmode on cpu). This repo will work in my build? CPU Not yet purchased :) Many users used this motherboard and coffee lake cpu on windows and don't have problem. What about MacOS?)

**Comment by BrushXue** [comment]
> Hey! I have z170i-Pro-Gaming motherboard and i want use cpu i5 9400f (I know about firmware bios and using pinmode on cpu). This repo will work in my build? CPU Not yet purchased :) Many users used this motherboard and coffee lake cpu on windows and don't have problem. What about MacOS?)

Hello.

I heard about this trick. If I remember correctly, you need a programmer to flash customized BIOS.
The problem is SMBIOS. You want to build a hybrid Skylake+Coffeelake system. I guess it will still work because extra CPU cores don’t  require a kext, and SSDTs are only for motherboard. However I can not guarantee this. Anyway you need to make sure your hybrid system can run Windows first.

**Comment by yehbr** [comment]
Hello. I have flash programmer. If my hybrid system will work on windows and system stably means hackintosh will work to? Anyway I will try it) Thanks.)

**Comment by BrushXue** [comment]
Found something from a Chinese forum:
![9C6CAEF6-270F-45CB-A198-B01EAFAD6543](https://user-images.githubusercontent.com/12702149/94342392-c750b800-ffde-11ea-8b72-c98a31e5a3d2.jpeg)
Translation:
Selling 9400F and ASUS Z170AR for CNY ¥1200
Flashed BIOS to support 8th & 9th gen CPU. Now runs Hackintosh and feels good.

So I guess it works. Good luck.

**Comment by yehbr** [comment]
> Found something from a Chinese forum:
> ![9C6CAEF6-270F-45CB-A198-B01EAFAD6543](https://user-images.githubusercontent.com/12702149/94342392-c750b800-ffde-11ea-8b72-c98a31e5a3d2.jpeg)
> Translation:
> Selling 9400F and ASUS Z170AR for CNY ¥1200
> 123 days ago
> Flashed BIOS to support 8th & 9th gen CPU. Now it runs Hackintosh and feels good.
> 
> So I guess it works. Good luck.

Thank you so much! I think this will worked!

**Comment by yehbr** [comment]
Hey, again. I did it. Cpu i5 9400f (coffeelake mode + pinmode) work on z170i pro gaming with your repo. But have one little problem, after sleep my usb mouse disconnects, when reconnecting mouse work again. Anyway thanks, studying opencore.
![aboutmac](https://user-images.githubusercontent.com/975612/127200174-3582dd89-384a-4b24-b854-ca0f9e379889.png)

**Comment by BrushXue** [comment]
Sorry I sold my desktop and bought a M1. So I won’t be able to reproduce any issue. My recommendation would be never put you hackintosh to sleep.
