### ISSUE TITLE
BIOS Version

### ISSUE THREAD

**Issue by gkankanh** [BrushXue/Z170i-Pro-Gaming-OpenCore#10]
Good Work. Thanks for sharing. I have the same MB but my BIOS does not have a cfglock option.
Can you please let me know your BIOS version.
Thanks

**Comment by BrushXue** [comment]
3805(latest)
https://dlcdnets.asus.com/pub/ASUS/mb/LGA1151/Z170I_PRO_GAMING/Z170I-PRO-GAMING-ASUS-3805.zip

**Comment by gkankanh** [comment]
Thanks.
