### ISSUE TITLE
Reboot_Loop

### ISSUE THREAD

**Issue by Wesleyvw** [BrushXue/Z170i-Pro-Gaming-OpenCore#11]
I'm using the same Z170 mobo and the same CPU. It get's me into the setup/installation but after the first reboot after installation it keeps restarting. Using the same BIOS settings, any thoughts?

**Comment by Wesleyvw** [comment]
First, thanks for your reply! I tried the 0.6.5 version but it won't change anything. Really don't get it, same motherboard, same CPU. I doublechecked all BIOS settings and in the 0.6.5 version EFI I only did change the config.plist items:

- SystemSerialNumber
- MLB
- SystemUUID
- UIScale to 01
- boot-args = -v debug=0x100

I formatted my SATA disk as Mac OS Extended (Journaled) with a GUID Partition Map.
I run the setup and when the screen hits the 11 minutes remaining it reboots. I checked some youtube installation video's and this reboot at 11 min remaining seems to be normal as the first part of the installation is done. After the reboot it should continue with the installation I guess.

This is the information I see in a flash second before the first reboot:
(No errors I guess, just the verbose messages for a reboot?)

https://pasteboard.co/JVcDtZR.jpg

Now I'm trying to figure out where to focus on, BIOS? Kexts? Etc. When no information and just reboots it could be anything. If you have any ideas feel free to share :)

**Comment by BrushXue** [comment]
Maybe try APFS? I've been using it for a year without any issue. I included HFSPlus.efi but haven't really tested it. That might be your problem.

**Comment by BrushXue** [comment]
HFS+ is a very old file system (1998) and is not optimized for SSD. All new Macs use APFS by default so there's no reason for us to choose the deprecated one.
Headless mode means iGPU does not output display content. It works as a hardware accelerator(e.g. FCPX HW encoding). 
In your case, you need to do the following things:
1. Disable dGPU in OpenCore. https://dortania.github.io/OpenCore-Install-Guide/extras/spoof.html
2. Use the desktop default framebuffer for HD530 https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/intel-gpu.html#skylake-6xxx
3. Use motherboard DP if possible. HDMI is always troublesome.

**Comment by Wesleyvw** [comment]
Great! I'm using the iGPU now and the 'About this Mac' says Graphics: Intel HD Graphics 530 7MB. 
(0x19120000 for AAPL,ig-platform-id) 

I've been struggling a few hours now to get proper hardware acceleration instead of 7MB but that's none of your problems :) But feel free to reply of you want :P Otherwise, thank you again for sharing your OpenCore version of ASUS Z170i and for your help, I couldn't do this without you!
