### ISSUE TITLE
layout-id

### ISSUE THREAD

**Issue by bigjimmy546** [BrushXue/Z170i-Pro-Gaming-OpenCore#12]
你好，我也是使用这一款MB，
我尝试着使用你CONFIG里面的audio layout-id data AQAAAA==
出现了错误

请问如果是 layout-id  number的话应该使用那一个？谢谢

**Comment by BrushXue** [comment]
这台电脑我已经出手了，没办法再测试。理论上主板都一样的。

**Comment by bigjimmy546** [comment]
好的，謝謝你
