### ISSUE TITLE
HD530 config.plist has merging confilcts

### ISSUE THREAD

**Issue by wenq1** [BrushXue/Z170i-Pro-Gaming-OpenCore#13]
Please check HD530 branch's config.plist. It is not a complete file, and a merging conflict needs to be resolved. I think you have accidentally checked that in

**Comment by BrushXue** [comment]
Hello,

I don’t own the hardware now. If you are interested to maintain this repo I can transfer it to you.

**Comment by bigjimmy546** [comment]
newest config file is not valid format, thanks

**Comment by BrushXue** [comment]
> newest config file is not valid format, thanks

Hello,

I don’t own the hardware now. If you are interested to maintain this repo I can transfer it to you.

**Comment by BrushXue** [comment]
Updated
