### ISSUE TITLE
HEVC disable

### ISSUE THREAD

**Issue by fidelio959** [BrushXue/Z170i-Pro-Gaming-OpenCore#2]
Hello mate, I have the same configuration as yours but with no external GPU. I only use HD530 for everything. Can you tell if you have HECV working on your system? Mine is not enable and did not find anything to figure it out. Thank you for your support. I have Big Sur beta installed on my system and works fine.

![Schermata 2020-11-01 alle 19 59 35](https://user-images.githubusercontent.com/73795114/97811748-d2050980-1c7c-11eb-972b-4520a246626e.png)

**Comment by BrushXue** [comment]
Hello,
My iGPU supports HEVC in 10.15
<img width="934" alt="Screen Shot 2020-11-02 at 10 30 57 AM" src="https://user-images.githubusercontent.com/12702149/97886960-44b2cb00-1cf7-11eb-9713-e42f1701e377.png">
I haven't tried Big Sur yet because I'm using this Hackintosh everyday and don't want to risk.

**Comment by fidelio959** [comment]
I can assure that beta 11 is really stable and I had not relevant problems in using it. Anyway I will going on seek for any workaround for it. Thank u.

**Comment by BrushXue** [comment]
I agree with you. I have it installed on my MacBook. However one of the
major software I use is not supported yet.

**Comment by BrushXue** [comment]
> I can assure that beta 11 is really stable and I had not relevant problems in using it. Anyway I will going on seek for any workaround for it. Thank u.

I found that the software I use has a RC version which supports Big Sur. Will consider an upgrade when I have more time.

**Comment by fidelio959** [comment]
This is a great new. I will wait for you response about hevc and other possible workaround.

**Comment by BrushXue** [comment]
I’m doing a fresh reinstall on my MacBook. Once all softwares are confirmed stable I’ll do it on my Hackintosh.

**Comment by BrushXue** [comment]
> This is a great new. I will wait for you response about hevc and other possible workaround.

I updated to Big Sur and HEVC is working
![Screen Shot 2020-11-15 at 8 06 28 AM](https://user-images.githubusercontent.com/12702149/99185712-9dcc2700-2719-11eb-8c31-9ecb44257f8b.png)

**Comment by fidelio959** [comment]
this is a great news! can you share with me your config.plist? I think that there is something I am missing in mine. thank you

**Comment by BrushXue** [comment]
The config file is already in the GitHub repo.

**Comment by fidelio959** [comment]
I had a try using your config.plist but I had a boot problem due to HD530 value. I changed it to 00001219 since I have monitor connected to it but in this case I lost HEVC and airplay icon on taskbar. I think that there is something wrong with my igpu settings. I will continue working on it and let you know.

**Comment by BrushXue** [comment]
Hello,

Do you have all of those following keys?

KeyTypeValue
AAPL,ig-platform-id Data 00001219
framebuffer-patch-enable Data 01000000
framebuffer-stolenmem Data 00003001
framebuffer-fbmem Data 00009000
device-id Data 1B190000

Best regards

**Comment by fidelio959** [comment]
Hello for some strange reason HEVC is working now. I clean my config.plist and kext folder and after a reboot it worked. Thank you for your support. My next step is to buy a sapphire external video cards and install it. Best regards.
