### ISSUE TITLE
After sleep not play YouTube in safari and not view built-in wallpapers in settings

### ISSUE THREAD

**Issue by Sheripov** [BrushXue/Z170i-Pro-Gaming-OpenCore#4]
Hello! I have BigSur with you config(thank you for this). I find some issue when wake after sleep. 

- [ ] 1. Do not play YouTube video(only in safari).
- [ ] 2. Don't view built-in wallpapers in settings
Can you help me with it?

**Comment by BrushXue** [comment]
Hello,

I don’t have any issue watching YouTube after sleep. And my wallpaper works normally.
Could you please provide your hardware spec?

Best

**Comment by Sheripov** [comment]
1. ASUS z170i pro gaming (coffee lake modded)
2. Processor is [QQLS](https://aliexpress.ru/item/4001201770134.html?spm=a2g0o.productlist.0.0.33372cb3OJ9XhD&algo_pvid=9f060c97-5917-42d1-bca7-3eca05ddc181&algo_expid=9f060c97-5917-42d1-bca7-3eca05ddc181-0&btsid=0b8b034c16064176090483279e820d&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_) (engineer version of i9-9980HK) 
[There are my EFI and logs](https://drive.google.com/drive/folders/1Q0hEEOsmbreXAdrskLK2lvL2XVHX__A_?usp=sharing)

**Comment by BrushXue** [comment]
Hello,

Are you using intel GPU (UHD 630) only? There is an article talking about how to choose the correct smbios. (in Chinese, you need translation)
https://blog.mrzorg.top/Hackintosh/2020-04-10-hackintosh-smbios-settings/
I saw you are using **iMac19,1** smbios, which means you need a AMD GPU to work together with UHD 630. Probably you need **macmini8,1** so the Intel GPU can work properly.

Best

**Comment by Sheripov** [comment]
Now with macmini8.1 panic kernel
![Uploading DF861ED9-B0F3-4C3F-BF07-DEA510DC4D93.jpeg…]()

**Comment by Sheripov** [comment]
Do you now why when I set smbios MacBookPro16,1 does't work any usb hub?

**Comment by BrushXue** [comment]
Sorry I have never tried to use laptop smbios. This configuration only works with Z170+Skylake. If you mix up other CPUs it's beyond me knowledge.
