### ISSUE TITLE
你好大佬，小白求问。

### ISSUE THREAD

**Issue by vivikuyo** [BrushXue/Z170i-Pro-Gaming-OpenCore#6]
你好大佬,首先非常感谢您的分享.
今天突然发现您分享了big sur的oc配置，我尝试并成功进入系统，但是有一点点小问题，.所以求教一下
我的平台配置跟您一样z170+6700k
不过我的主板是:（MSI）Z170A KRAIT GAMING 3X
内存:铂胜运动LT系列DDR4 2400
显卡:rx580 2304 4G 矿卡
硬盘:东芝TR200

**问题1：我主板的usb映射跟您的有所区别，我尝试学习用hackintoll查看修改，但是很多接口插入后不可用，有几个插口虽然能用，但是hackintoll中却没有显示，所以想请教下如何重置，重新映射？**

**问题2：我试了下，主板的hdmi接口不工作，性能上有无影响？**

下面是我芯片组的部分信息,您过过眼,请指教，谢谢？
芯片组• Z170 芯片组
 
内存• 4 条 DDR4 内存插槽，最高支持总容量 64GB- 支持 DDR4 3600(OC)/ 3200(OC)/ 3000(OC)/ 2800(OC)/ 2600(OC)/ 2400/ 2133 MHz*• 双通道内存架构• 支持 ECC、未缓冲处理的内存- ECC UDIMM 内存 (非-ECC 模式)• 支持 Intel® Extreme Memory Profile (XMP)* 如需兼容内存的详细信息，请参阅 www.msi.com
 
插槽• 3 个 PCIe 3.0 x16 插槽 (支持 x16/x0/x4 或 x8/x8/x4 模式)• 4 个 PCIe 3.0 x1 插槽
 
板载显卡输出接口• 1 个 HDMI™ 接口，支持最高分辨率 4096x2160@24Hz, 2560x1600@60Hz• 1 个 DVI-D 接口，支持最高分辨率 1920x1200@60Hz
 
USB• Intel® Z170 芯片组- 6 个 USB 3.1 Gen1 (SuperSpeed USB) 接口 (2 个位于背板，4 个通过板载 USB 3.1 Gen1 接口提供)- 8 个 USB 2.0 (High-speed USB) 接口 (4 个位于背板，4 个通过板载 USB 2.0 接口提供)
 
板载声卡• Realtek® ALC1150 译码芯片- 7.1 声道高音质音效- 支持 S/PDIF 输出
 
板载网卡 • 1 个 Intel® I219-V Gigabit 网络控制器

韧体 (BIOS)• 此主板的BIOS 提供"即插即用" 功能，能自动侦测板子上的外围设备和扩充卡• 此主板提供桌面管理接口(DMI)功能，能记录你主板的规格

https://cn.msi.com/Motherboard/Z170A-KRAIT-GAMING-3X/Specification 主板官网连接

**Comment by BrushXue** [comment]
不要把我捧这么高...我只是按照原版教程一步一步做的把EFI发出来分享。换一块主板我也不会弄。

**Comment by vivikuyo** [comment]
> 不要把我捧这么高...我只是按照原版教程一步一步做的，然后把EFI发出来分享。换一块主板我也不会弄。
> 尝试回答：1. 重做USB映射之前需要USBinjectall.kext
> 2. 黑苹果少接HDMI，Mac不连DP容易出现各种玄学故障。

非常感谢回复答疑，刚才从黑果小兵那里发现了重映射的方式，不过现在还有点小问题，usb3.0接口只能在usb2.0模式下识别使用，并且hackintool里也只显示hs**,xs**都没反应，是否还需要usb3.0的驱动?
关于显示器我用了两个，一个显卡dp接主显，一个主板hdmi接副显，如果问题不大的话我就副显hdmi接显卡上。

**Comment by BrushXue** [comment]
主板原生的USB3.0不需要驱动

**Comment by BrushXue** [comment]
> 关于显示器我用了两个，一个显卡dp接主显，一个主板hdmi接副显，如果问题不大的话我就副显hdmi接显卡上。

我刚反应过来你是显卡接一个主板接一个，据我所知应该是不可能的。你要么选择核显输出，不插独显。要么选择核显做辅助计算，独显输出。

**Comment by vivikuyo** [comment]
好的，再次表示感谢，我usb用的不多，就先凑活在2.0模式工作吧，黑苹果之路已经看到尽头，在这最后的路程里，希望大佬能持续更新下去，谢谢~！

**Comment by BrushXue** [comment]
> 好的，再次表示感谢，我usb用的不多，就先凑活在2.0模式工作吧，黑苹果之路已经看到尽头，在这最后的路程里，希望大佬能持续更新下去，谢谢~！

这你得问苹果，什么时候iMac17,1被淘汰了就走到尽头了。
