### ISSUE TITLE
禁用CSM后显卡自检无法通过

### ISSUE THREAD

**Issue by fooevr** [BrushXue/Z170i-Pro-Gaming-OpenCore#8]
作者你好，感谢提供这个EFI。我使用集成显卡安装通过了，但是使用蓝宝石 RX580安装时按照要求关闭CSM后，会导致系统无法通过显卡自检。 但是显卡官网是说明支持UEFI BIOS。不知道关闭CSM是否是必须的？

**Comment by BrushXue** [comment]
开启CSM有可能导致OpenCore界面分辨率不正常，进系统以后没有影响。
