### ISSUE TITLE
关于引导反复重启问题

### ISSUE THREAD

**Issue by 68516463** [BrushXue/Z170i-Pro-Gaming-OpenCore#9]
作者你好，麻烦请教你一下，我使用你的efi，可以进入安装界面，但是一直在安装界面反复重启

而且我的bio是里面没有这3个选项
Primary Display | PCIE
iGPU-Multi-Monitor | Enabled
DVMT Pre-Allocated | 128M

cpu是魔改的ql3x
显卡蓝宝石rx560
网卡还没有更换博通免驱卡

安装big sur在系统安装界面反复重启，我看别人同样是ql3x的cpu，不过不是这块主板
说是在启动参数加入-disablegfxfirmware（由于主板ME问题导致睡眠异常，不加此参数会卡核显）
我尝试加入后还是反复重启，求教是什么问题引起的？

**Comment by BrushXue** [comment]
你这不是正式版CPU，主板BIOS还刷过，我真没法帮你...
